micronaut:
  application:
    name: SplitNice
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/example
    username: ${mysql_db_local_user}
    password: ${mysql_db_local_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
#jpa:
#  default:
#    packages-to-scan: "com.splitnice"
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#      show_sql: true
netty:
  default:
    allocator:
      max-order: 3
